# Generated by Django 3.0.6 on 2020-07-25 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics_app', '0008_auto_20200717_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('archieved', models.BooleanField(default=False)),
                ('related_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_warrnings_bans_app_report', to='topics_app.Post')),
                ('reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warrning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('deisplay_reason_on_related_object', models.BooleanField(default=True)),
                ('hide_related_object', models.BooleanField(default=True)),
                ('related_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_warrnings_bans_app_warrning', to='topics_app.Post')),
                ('related_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_warrnings_bans_app_warrning', to='reports_warrnings_bans_app.Report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_warrnings_bans_app_warrning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('deisplay_reason_on_related_object', models.BooleanField(default=True)),
                ('hide_related_object', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('related_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_warrnings_bans_app_ban', to='topics_app.Post')),
                ('related_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_warrnings_bans_app_ban', to='reports_warrnings_bans_app.Report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_warrnings_bans_app_ban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
