# Generated by Django 3.0.6 on 2020-05-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
