# Generated by Django 3.0.6 on 2020-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0002_auto_20200625_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_updated',
            new_name='edited_datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='last_updated',
            new_name='edited_datetime',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='times_edited',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='last_post_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='times_edited',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
