# Generated by Django 3.0.6 on 2020-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0003_auto_20200625_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='times_edited',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='times_edited',
            field=models.SmallIntegerField(null=True),
        ),
    ]
