# Generated by Django 3.0.6 on 2020-07-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0004_auto_20200625_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='edited_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
