# Generated by Django 3.0.6 on 2020-07-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_app', '0007_remove_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_be_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_topic_post',
            field=models.BooleanField(default=False),
        ),
    ]
