# Generated by Django 3.0.6 on 2020-05-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=248, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=248, null=True)),
                ('can_add_new_posts', models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group', null=True, related_name='subboard_can_add_new_posts', to='auth.Group')),
                ('can_view_group', models.ManyToManyField(blank=True, help_text='What groups will ba bale to view given this Board/Group', null=True, related_name='subboard_can_view_group', to='auth.Group')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_board', to='boards_app.Board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=248, null=True)),
                ('can_add_new_posts', models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group', null=True, related_name='boardgroup_can_add_new_posts', to='auth.Group')),
                ('can_view_group', models.ManyToManyField(blank=True, help_text='What groups will ba bale to view given this Board/Group', null=True, related_name='boardgroup_can_view_group', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='board',
            name='board_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='boards_app.BoardGroup'),
        ),
        migrations.AddField(
            model_name='board',
            name='can_add_new_posts',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group', null=True, related_name='board_can_add_new_posts', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='can_view_group',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba bale to view given this Board/Group', null=True, related_name='board_can_view_group', to='auth.Group'),
        ),
    ]
