# Generated by Django 3.0.6 on 2020-05-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_group',
            new_name='parent',
        ),
    ]
