# Generated by Django 3.0.6 on 2020-05-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('boards_app', '0002_auto_20200523_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subboard',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='can_add_new_posts',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group, Aviable after creation', null=True, related_name='board_can_add_new_posts', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='board',
            name='can_view_group',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba bale to view given this Board/Group  Aviable after creation', null=True, related_name='board_can_view_group', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='can_add_new_posts',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group, Aviable after creation', null=True, related_name='boardgroup_can_add_new_posts', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='can_view_group',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba bale to view given this Board/Group  Aviable after creation', null=True, related_name='boardgroup_can_view_group', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='subboard',
            name='can_add_new_posts',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group, Aviable after creation', null=True, related_name='subboard_can_add_new_posts', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='subboard',
            name='can_view_group',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba bale to view given this Board/Group  Aviable after creation', null=True, related_name='subboard_can_view_group', to='auth.Group'),
        ),
    ]
