# Generated by Django 3.0.6 on 2020-06-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('boards_app', '0003_auto_20200524_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='parent',
        ),
        migrations.AddField(
            model_name='board',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='position',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='position',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='SubBoard',
        ),
    ]
