# Generated by Django 3.0.6 on 2020-06-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('boards_app', '0004_auto_20200623_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='board',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
