# Generated by Django 3.0.6 on 2020-06-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0006_auto_20200624_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('can_view', 'Can user view given Group/Board'), ('can_add_new_topics', 'Can user add new topics'), ('can_add_new_posts', 'Can user add new posts'))},
        ),
        migrations.AlterModelOptions(
            name='boardgroup',
            options={'permissions': (('can_view', 'Can user view given Group/Board'), ('can_add_new_topics', 'Can user add new topics'), ('can_add_new_posts', 'Can user add new posts'))},
        ),
    ]
