# Generated by Django 3.0.6 on 2020-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0007_auto_20200625_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelOptions(
            name='boardgroup',
            options={},
        ),
        migrations.AddField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('paid', 'Paid'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('paid', 'Paid'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
            preserve_default=False,
        ),
    ]
