# Generated by Django 3.0.6 on 2020-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0008_auto_20200625_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='add_new_posts_restictions',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='add_new_topics_restrictions',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='add_new_posts_restictions',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='add_new_topics_restrictions',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], max_length=124),
        ),
    ]
