# Generated by Django 3.0.6 on 2020-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('boards_app', '0009_auto_20200625_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='can_add_new_posts',
            new_name='new_posts_groups',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='can_view_group',
            new_name='visibility_groups',
        ),
        migrations.RenameField(
            model_name='boardgroup',
            old_name='can_add_new_posts',
            new_name='new_posts_groups',
        ),
        migrations.RenameField(
            model_name='boardgroup',
            old_name='can_view_group',
            new_name='visibility_groups',
        ),
        migrations.AddField(
            model_name='board',
            name='new_topics_groups',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group, Aviable after creation', null=True, related_name='board_can_add_new_topics', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='boardgroup',
            name='new_topics_groups',
            field=models.ManyToManyField(blank=True, help_text='What groups will ba able to add new topics to this Board/Group, Aviable after creation', null=True, related_name='boardgroup_can_add_new_topics', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='board',
            name='add_new_posts_restictions',
            field=models.CharField(choices=[('registered', 'Registered'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='registered', max_length=124),
        ),
        migrations.AlterField(
            model_name='board',
            name='add_new_topics_restrictions',
            field=models.CharField(choices=[('registered', 'Registered'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='registered', max_length=124),
        ),
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='add_new_posts_restictions',
            field=models.CharField(choices=[('registered', 'Registered'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='registered', max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='add_new_topics_restrictions',
            field=models.CharField(choices=[('registered', 'Registered'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='registered', max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('selected', 'Selected Groups'), ('admins', 'Admins'), ('superuser', 'Superusers')], default='all', max_length=124),
        ),
    ]
