# Generated by Django 3.0.6 on 2020-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('boards_app', '0010_auto_20200625_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='add_new_posts_restictions',
            field=models.IntegerField(choices=[(5, 'All'), (4, 'Registered'), (3, 'Selected Groups'), (2, 'Admins'), (1, 'Superusers'), (0, 'None')], default='registered', help_text='Lowest user group to be able to add new posts', max_length=124),
        ),
        migrations.AlterField(
            model_name='board',
            name='add_new_topics_restrictions',
            field=models.IntegerField(choices=[(5, 'All'), (4, 'Registered'), (3, 'Selected Groups'), (2, 'Admins'), (1, 'Superusers'), (0, 'None')], default='registered', help_text='Lowest user group to be able to add new topics', max_length=124),
        ),
        migrations.AlterField(
            model_name='board',
            name='new_posts_groups',
            field=models.ManyToManyField(blank=True, help_text="if new post restricions is set to 'Selected groups' set the groups", related_name='board_can_add_new_posts', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='board',
            name='new_topics_groups',
            field=models.ManyToManyField(blank=True, help_text="if new topics restricions is set to 'Selected groups' set the groups", related_name='board_can_add_new_topics', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.IntegerField(choices=[(5, 'All'), (4, 'Registered'), (3, 'Selected Groups'), (2, 'Admins'), (1, 'Superusers'), (0, 'None')], default='all', help_text='Lowest user group to be able to see Group/Board', max_length=124),
        ),
        migrations.AlterField(
            model_name='board',
            name='visibility_groups',
            field=models.ManyToManyField(blank=True, help_text="if visibility is set to 'Selected groups' set the groups", related_name='board_can_view_group', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='add_new_posts_restictions',
            field=models.IntegerField(choices=[(5, 'All'), (4, 'Registered'), (3, 'Selected Groups'), (2, 'Admins'), (1, 'Superusers'), (0, 'None')], default='registered', help_text='Lowest user group to be able to add new posts', max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='add_new_topics_restrictions',
            field=models.IntegerField(choices=[(5, 'All'), (4, 'Registered'), (3, 'Selected Groups'), (2, 'Admins'), (1, 'Superusers'), (0, 'None')], default='registered', help_text='Lowest user group to be able to add new topics', max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='new_posts_groups',
            field=models.ManyToManyField(blank=True, help_text="if new post restricions is set to 'Selected groups' set the groups", related_name='boardgroup_can_add_new_posts', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='new_topics_groups',
            field=models.ManyToManyField(blank=True, help_text="if new topics restricions is set to 'Selected groups' set the groups", related_name='boardgroup_can_add_new_topics', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='visibility',
            field=models.IntegerField(choices=[(5, 'All'), (4, 'Registered'), (3, 'Selected Groups'), (2, 'Admins'), (1, 'Superusers'), (0, 'None')], default='all', help_text='Lowest user group to be able to see Group/Board', max_length=124),
        ),
        migrations.AlterField(
            model_name='boardgroup',
            name='visibility_groups',
            field=models.ManyToManyField(blank=True, help_text="if visibility is set to 'Selected groups' set the groups", related_name='boardgroup_can_view_group', to='auth.Group'),
        ),
    ]
