# Generated by Django 3.0.6 on 2020-07-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0012_auto_20200710_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='boardgroup',
            options={'ordering': ['position']},
        ),
    ]
